### PR TITLE
correct use of future_builtin

### PR DESCRIPTION
**Pull request by dacoex**
on linux mint 17 with Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
```
import future_builtins

future_builtins?
Type:        module
String form: <module 'future_builtins' from '/usr/lib/python2.7/lib-dynload/future_builtins.x86_64-linux-gnu.so'>
File:        /usr/lib/python2.7/lib-dynload/future_builtins.x86_64-linux-gnu.so
Docstring:
This module provides functions that will be builtins in Python 3.0,
but that conflict with builtins that already exist in Python 2.x.

Functions:

ascii(arg) -- Returns the canonical string representation of an object.
filter(pred, iterable) -- Returns an iterator yielding those items of 
       iterable for which pred(item) is true.
hex(arg) -- Returns the hexadecimal representation of an integer.
map(func, *iterables) -- Returns an iterator that computes the function 
    using arguments from each of the iterables.
oct(arg) -- Returns the octal representation of an integer.
zip(iter1 [,iter2 [...]]) -- Returns a zip object whose .next() method 
    returns a tuple where the i-th element comes from the i-th iterable 
    argument.

The typical usage of this module is to replace existing builtins in a
module's namespace:
 
from future_builtins import ascii, filter, map, hex, oct, zip
```

### CODE REVIEW

**Comment by tonysyu** [comment]
@dacoex: Thanks for the PR, but I don't believe this is correct. `mpltools` requires the `future` package, which defines `future.builtins`. I think the rationale for this apparent duplication is that importing `future_builtins` is not actually valid in Python 3.

**Comment by dacoex** [comment]
ok, I found the relevant package:
http://packages.ubuntu.com/trusty/python-concurrent.futures

as the page says: "Backport of the concurrent.futures package from Python 3.2"
https://pypi.python.org/pypi/futures

**Comment by tonysyu** [comment]
Actually, this is the case of some *really* bad naming. You're going to want this package: https://pypi.python.org/pypi/future. Notice there's no "s" at the end.

BTW, how did you install `mpltools`? I actually thought this dependency would be picked up by `pip` (due to `requirements.txt`), and when I run `python setup.py install`, it is explicitly checked (due to `install_requires` in `setup.py`).

I'm going to close this PR, since it doesn't seem like the appropriate fix in this case.

**Comment by dacoex** [comment]
>Actually, this is the case of some really bad naming. You're going to want this package: >https://pypi.python.org/pypi/future. Notice there's no "s" at the end.
OK.

>BTW, how did you install mpltools?
I am trying to build a debian/ubuntu package so that it will be installable and updated via the package manager:
https://code.launchpad.net/~pythonxy/+archive/ubuntu/pythonxy-devel/+packages?field.name_filter=mpltools

> I actually thought this dependency would be picked up by pip (due to requirements.txt), and when I run python setup.py install, it is explicitly checked (due to install_requires in setup.py).
It does. But the linux package managers rely on packages available to the distribution.

So the future is only available as future_builtins. But I guess it's the same functionality.
I tried to clarify:
https://askubuntu.com/questions/592280/which-ubuntu-package-provides-the-pypi-future-package

If we really need
https://pypi.python.org/pypi/future
then, I would need to package that one, too.

**Comment by dacoex** [comment]
Via websearch for "matplotlib errorfill" I found out that it is was stated at
http://matplotlib.org/1.2.1/users/github_stats.html that the functionality had been integraded into mpl with the PR
https://github.com/matplotlib/matplotlib/pull/1010/files

But your function has the nice legend creation feature. See also:
https://github.com/matplotlib/matplotlib/issues/4214

**Comment by dacoex** [comment]
The recent change in mpl
https://github.com/matplotlib/matplotlib/issues/4214#issuecomment-78538667
reduces my (personal) need in mpltools at this time although it has nice features such as .

Thanks for attending my comments/questions.

**Pull request closed without merging**
